#!/usr/bin/env python3
"""Create the small, self-contained sample image module used by GitHub Pages."""

from __future__ import annotations

import argparse
import base64
import io
from pathlib import Path

from PIL import Image, ImageEnhance, ImageOps


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("image", type=Path)
    parser.add_argument("--output", type=Path, default=Path("sample-image.js"))
    args = parser.parse_args()

    with Image.open(args.image) as original:
        image = ImageOps.exif_transpose(original).convert("RGB")
        image.thumbnail((900, 1150), Image.Resampling.LANCZOS)
        image = ImageEnhance.Contrast(image).enhance(1.06)
        payload = io.BytesIO()
        image.save(payload, format="JPEG", quality=72, optimize=True, progressive=True)

    encoded = base64.b64encode(payload.getvalue()).decode("ascii")
    args.output.write_text(
        "// Generated by scripts/embed_sample.py; source artwork by Sophia.\n"
        f'export const SOPHIA_IMAGE = "data:image/jpeg;base64,{encoded}";\n',
        encoding="utf-8",
    )
    print(f"wrote {args.output} ({args.output.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
